# Generated by Django 5.2.5 on 2025-08-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.IntegerField()),
                ('expected_duration', models.DurationField()),
                ('date', models.DateField()),
                ('scheduled_start_time', models.TimeField(blank=True, null=True)),
                ('scheduled_end_time', models.TimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
            ],
        ),
    ]
